-- Replace old symptom-based service types (28 rows) with the 156-service HVAC catalog
-- Clean names without category prefix; category stored in separate column for UI grouping

-- Delete existing rows for client_id = 1
DELETE FROM service_types WHERE client_id = 1;

-- Insert the new 156 services
INSERT INTO service_types (name, category, duration_minutes, urgency, customer_phrases, sort_order, is_active, client_id) VALUES
  -- Diagnostics (24 services)
  ('HVAC System Diagnostic', 'Diagnostics', 45, 'standard', '{}', 1, true, 1),
  ('AC Diagnostic', 'Diagnostics', 45, 'standard', '{}', 2, true, 1),
  ('Furnace Diagnostic', 'Diagnostics', 45, 'standard', '{}', 3, true, 1),
  ('Heat Pump Diagnostic', 'Diagnostics', 45, 'standard', '{}', 4, true, 1),
  ('Boiler Diagnostic', 'Diagnostics', 60, 'standard', '{}', 5, true, 1),
  ('Thermostat Diagnostic', 'Diagnostics', 30, 'standard', '{}', 6, true, 1),
  ('Electrical Diagnostic', 'Diagnostics', 60, 'standard', '{}', 7, true, 1),
  ('Airflow Diagnostic', 'Diagnostics', 45, 'standard', '{}', 8, true, 1),
  ('Static Pressure Test', 'Diagnostics', 60, 'standard', '{}', 9, true, 1),
  ('Refrigerant Leak Detection', 'Diagnostics', 60, 'standard', '{}', 10, true, 1),
  ('Refrigerant Pressure Check', 'Diagnostics', 45, 'standard', '{}', 11, true, 1),
  ('Compressor Diagnostic', 'Diagnostics', 60, 'standard', '{}', 12, true, 1),
  ('Blower Motor Diagnostic', 'Diagnostics', 45, 'standard', '{}', 13, true, 1),
  ('Condenser Fan Diagnostic', 'Diagnostics', 45, 'standard', '{}', 14, true, 1),
  ('Ignition System Diagnostic', 'Diagnostics', 45, 'standard', '{}', 15, true, 1),
  ('Gas Pressure Test', 'Diagnostics', 45, 'standard', '{}', 16, true, 1),
  ('Combustion Analysis', 'Diagnostics', 60, 'standard', '{}', 17, true, 1),
  ('Heat Exchanger Inspection', 'Diagnostics', 60, 'standard', '{}', 18, true, 1),
  ('Indoor Air Quality Test', 'Diagnostics', 60, 'standard', '{}', 19, true, 1),
  ('Duct Leakage Test', 'Diagnostics', 90, 'standard', '{}', 20, true, 1),
  ('Energy Efficiency Assessment', 'Diagnostics', 90, 'standard', '{}', 21, true, 1),
  ('Load Calculation (Manual J)', 'Diagnostics', 120, 'standard', '{}', 22, true, 1),
  ('HVAC System Inspection', 'Diagnostics', 60, 'standard', '{}', 23, true, 1),
  ('Seasonal HVAC Inspection', 'Diagnostics', 60, 'standard', '{}', 24, true, 1),

  -- Maintenance (24 services)
  ('HVAC Preventive Maintenance', 'Maintenance', 90, 'scheduled', '{}', 25, true, 1),
  ('AC Tune-Up', 'Maintenance', 75, 'scheduled', '{}', 26, true, 1),
  ('Furnace Tune-Up', 'Maintenance', 75, 'scheduled', '{}', 27, true, 1),
  ('Heat Pump Maintenance', 'Maintenance', 75, 'scheduled', '{}', 28, true, 1),
  ('Boiler Maintenance', 'Maintenance', 75, 'scheduled', '{}', 29, true, 1),
  ('Condenser Coil Cleaning', 'Maintenance', 90, 'scheduled', '{}', 30, true, 1),
  ('Evaporator Coil Cleaning', 'Maintenance', 90, 'scheduled', '{}', 31, true, 1),
  ('Blower Motor Service', 'Maintenance', 60, 'scheduled', '{}', 32, true, 1),
  ('Condenser Unit Maintenance', 'Maintenance', 60, 'scheduled', '{}', 33, true, 1),
  ('Air Handler Maintenance', 'Maintenance', 60, 'scheduled', '{}', 34, true, 1),
  ('Filter Replacement', 'Maintenance', 20, 'scheduled', '{}', 35, true, 1),
  ('Belt Replacement', 'Maintenance', 45, 'scheduled', '{}', 36, true, 1),
  ('Lubricate Moving Parts', 'Maintenance', 45, 'scheduled', '{}', 37, true, 1),
  ('Electrical Connection Tightening', 'Maintenance', 45, 'scheduled', '{}', 38, true, 1),
  ('Refrigerant Level Check', 'Maintenance', 45, 'scheduled', '{}', 39, true, 1),
  ('Capacitor Testing', 'Maintenance', 30, 'scheduled', '{}', 40, true, 1),
  ('Thermostat Calibration', 'Maintenance', 30, 'scheduled', '{}', 41, true, 1),
  ('Flame Sensor Cleaning', 'Maintenance', 45, 'scheduled', '{}', 42, true, 1),
  ('Burner Cleaning', 'Maintenance', 60, 'scheduled', '{}', 43, true, 1),
  ('Drain Line Cleaning', 'Maintenance', 45, 'scheduled', '{}', 44, true, 1),
  ('Vent Inspection', 'Maintenance', 45, 'scheduled', '{}', 45, true, 1),
  ('Safety Control Check', 'Maintenance', 45, 'scheduled', '{}', 46, true, 1),
  ('Fan Blade Cleaning', 'Maintenance', 45, 'scheduled', '{}', 47, true, 1),
  ('Inducer Motor Cleaning', 'Maintenance', 60, 'scheduled', '{}', 48, true, 1),

  -- Repairs (27 services)
  ('Thermostat Repair', 'Repairs', 45, 'standard', '{}', 49, true, 1),
  ('Thermostat Replacement', 'Repairs', 60, 'standard', '{}', 50, true, 1),
  ('Capacitor Replacement', 'Repairs', 45, 'standard', '{}', 51, true, 1),
  ('Contactor Replacement', 'Repairs', 60, 'standard', '{}', 52, true, 1),
  ('Blower Motor Replacement', 'Repairs', 120, 'standard', '{}', 53, true, 1),
  ('Condenser Fan Motor Replacement', 'Repairs', 120, 'standard', '{}', 54, true, 1),
  ('Inducer Motor Replacement', 'Repairs', 120, 'standard', '{}', 55, true, 1),
  ('Compressor Replacement', 'Repairs', 270, 'standard', '{}', 56, true, 1),
  ('Refrigerant Recharge', 'Repairs', 60, 'standard', '{}', 57, true, 1),
  ('Refrigerant Leak Repair', 'Repairs', 120, 'standard', '{}', 58, true, 1),
  ('TXV Replacement', 'Repairs', 120, 'standard', '{}', 59, true, 1),
  ('Expansion Valve Replacement', 'Repairs', 120, 'standard', '{}', 60, true, 1),
  ('Ignitor Replacement', 'Repairs', 45, 'standard', '{}', 61, true, 1),
  ('Flame Sensor Replacement', 'Repairs', 45, 'standard', '{}', 62, true, 1),
  ('Circuit Board Replacement', 'Repairs', 90, 'standard', '{}', 63, true, 1),
  ('Transformer Replacement', 'Repairs', 60, 'standard', '{}', 64, true, 1),
  ('Wiring Repair', 'Repairs', 120, 'standard', '{}', 65, true, 1),
  ('Breaker Replacement', 'Repairs', 60, 'standard', '{}', 66, true, 1),
  ('Gas Valve Replacement', 'Repairs', 90, 'standard', '{}', 67, true, 1),
  ('Pilot Assembly Repair', 'Repairs', 60, 'standard', '{}', 68, true, 1),
  ('Heat Exchanger Repair', 'Repairs', 180, 'standard', '{}', 69, true, 1),
  ('Condensate Pump Replacement', 'Repairs', 60, 'standard', '{}', 70, true, 1),
  ('Drain Pan Replacement', 'Repairs', 90, 'standard', '{}', 71, true, 1),
  ('Air Handler Repair', 'Repairs', 120, 'standard', '{}', 72, true, 1),
  ('Furnace Repair', 'Repairs', 120, 'standard', '{}', 73, true, 1),
  ('AC Repair', 'Repairs', 120, 'standard', '{}', 74, true, 1),
  ('Heat Pump Repair', 'Repairs', 120, 'standard', '{}', 75, true, 1),

  -- Installation (20 services)
  ('HVAC System Installation', 'Installation', 360, 'scheduled', '{}', 76, true, 1),
  ('HVAC System Replacement', 'Installation', 480, 'scheduled', '{}', 77, true, 1),
  ('Furnace Installation', 'Installation', 360, 'scheduled', '{}', 78, true, 1),
  ('Furnace Replacement', 'Installation', 360, 'scheduled', '{}', 79, true, 1),
  ('Central AC Installation', 'Installation', 360, 'scheduled', '{}', 80, true, 1),
  ('AC Replacement', 'Installation', 360, 'scheduled', '{}', 81, true, 1),
  ('Heat Pump Installation', 'Installation', 360, 'scheduled', '{}', 82, true, 1),
  ('Heat Pump Replacement', 'Installation', 360, 'scheduled', '{}', 83, true, 1),
  ('Boiler Installation', 'Installation', 360, 'scheduled', '{}', 84, true, 1),
  ('Boiler Replacement', 'Installation', 360, 'scheduled', '{}', 85, true, 1),
  ('Air Handler Installation', 'Installation', 240, 'scheduled', '{}', 86, true, 1),
  ('Mini-Split Installation', 'Installation', 240, 'scheduled', '{}', 87, true, 1),
  ('Mini-Split Multi-Zone Install', 'Installation', 360, 'scheduled', '{}', 88, true, 1),
  ('Thermostat Installation', 'Installation', 45, 'scheduled', '{}', 89, true, 1),
  ('Smart Thermostat Installation', 'Installation', 45, 'scheduled', '{}', 90, true, 1),
  ('Zoning System Installation', 'Installation', 240, 'scheduled', '{}', 91, true, 1),
  ('Zone Control Board Installation', 'Installation', 120, 'scheduled', '{}', 92, true, 1),
  ('Zone Damper Installation', 'Installation', 120, 'scheduled', '{}', 93, true, 1),
  ('Whole-House Fan Installation', 'Installation', 180, 'scheduled', '{}', 94, true, 1),
  ('Packaged Unit Installation', 'Installation', 360, 'scheduled', '{}', 95, true, 1),

  -- Ductwork (10 services)
  ('Ductwork Installation', 'Ductwork', 360, 'scheduled', '{}', 96, true, 1),
  ('Ductwork Replacement', 'Ductwork', 360, 'scheduled', '{}', 97, true, 1),
  ('Duct Repair', 'Ductwork', 120, 'standard', '{}', 98, true, 1),
  ('Duct Sealing', 'Ductwork', 180, 'scheduled', '{}', 99, true, 1),
  ('Duct Insulation', 'Ductwork', 180, 'scheduled', '{}', 100, true, 1),
  ('Air Duct Cleaning', 'Ductwork', 180, 'scheduled', '{}', 101, true, 1),
  ('Vent Installation', 'Ductwork', 120, 'scheduled', '{}', 102, true, 1),
  ('Vent Repair', 'Ductwork', 90, 'standard', '{}', 103, true, 1),
  ('Register Replacement', 'Ductwork', 45, 'standard', '{}', 104, true, 1),
  ('Return Air Installation', 'Ductwork', 180, 'scheduled', '{}', 105, true, 1),

  -- Ventilation (7 services)
  ('ERV Installation', 'Ventilation', 240, 'scheduled', '{}', 106, true, 1),
  ('HRV Installation', 'Ventilation', 240, 'scheduled', '{}', 107, true, 1),
  ('Ventilation Fan Installation', 'Ventilation', 120, 'scheduled', '{}', 108, true, 1),
  ('Exhaust Fan Installation', 'Ventilation', 120, 'scheduled', '{}', 109, true, 1),
  ('Attic Ventilation Installation', 'Ventilation', 240, 'scheduled', '{}', 110, true, 1),
  ('Dryer Vent Cleaning', 'Ventilation', 90, 'scheduled', '{}', 111, true, 1),
  ('Ventilation System Repair', 'Ventilation', 120, 'standard', '{}', 112, true, 1),

  -- Indoor Air Quality (11 services)
  ('Whole-House Air Purifier Installation', 'Indoor Air Quality', 120, 'scheduled', '{}', 113, true, 1),
  ('Electronic Air Cleaner Install', 'Indoor Air Quality', 120, 'scheduled', '{}', 114, true, 1),
  ('UV Light Installation', 'Indoor Air Quality', 90, 'scheduled', '{}', 115, true, 1),
  ('Humidifier Installation', 'Indoor Air Quality', 180, 'scheduled', '{}', 116, true, 1),
  ('Humidifier Repair', 'Indoor Air Quality', 90, 'standard', '{}', 117, true, 1),
  ('Dehumidifier Installation', 'Indoor Air Quality', 180, 'scheduled', '{}', 118, true, 1),
  ('Dehumidifier Repair', 'Indoor Air Quality', 90, 'standard', '{}', 119, true, 1),
  ('Air Scrubber Installation', 'Indoor Air Quality', 120, 'scheduled', '{}', 120, true, 1),
  ('Media Filter Installation', 'Indoor Air Quality', 60, 'scheduled', '{}', 121, true, 1),
  ('Carbon Filter Installation', 'Indoor Air Quality', 60, 'scheduled', '{}', 122, true, 1),
  ('HEPA Filter Installation', 'Indoor Air Quality', 60, 'scheduled', '{}', 123, true, 1),

  -- Controls (5 services)
  ('Thermostat Programming', 'Controls', 30, 'standard', '{}', 124, true, 1),
  ('HVAC Zoning Setup', 'Controls', 120, 'scheduled', '{}', 125, true, 1),
  ('Smart Home HVAC Integration', 'Controls', 90, 'scheduled', '{}', 126, true, 1),
  ('Building Automation Setup', 'Controls', 180, 'scheduled', '{}', 127, true, 1),
  ('Control Board Programming', 'Controls', 90, 'standard', '{}', 128, true, 1),

  -- System Design (4 services)
  ('HVAC System Design Consultation', 'System Design', 120, 'scheduled', '{}', 129, true, 1),
  ('Energy Efficiency Upgrade Consultation', 'System Design', 90, 'scheduled', '{}', 130, true, 1),
  ('HVAC Retrofit Planning', 'System Design', 120, 'scheduled', '{}', 131, true, 1),
  ('Duct Design Calculation', 'System Design', 120, 'scheduled', '{}', 132, true, 1),

  -- Commercial (11 services)
  ('Rooftop Unit Diagnostic', 'Commercial', 60, 'standard', '{}', 133, true, 1),
  ('Rooftop Unit Maintenance', 'Commercial', 90, 'scheduled', '{}', 134, true, 1),
  ('Rooftop Unit Repair', 'Commercial', 180, 'standard', '{}', 135, true, 1),
  ('Rooftop Unit Installation', 'Commercial', 480, 'scheduled', '{}', 136, true, 1),
  ('Make-Up Air Unit Service', 'Commercial', 180, 'scheduled', '{}', 137, true, 1),
  ('VAV Box Service', 'Commercial', 120, 'scheduled', '{}', 138, true, 1),
  ('Cooling Tower Inspection', 'Commercial', 120, 'scheduled', '{}', 139, true, 1),
  ('Chiller Inspection', 'Commercial', 180, 'scheduled', '{}', 140, true, 1),
  ('Chiller Repair', 'Commercial', 240, 'standard', '{}', 141, true, 1),
  ('Walk-In Cooler Repair', 'Commercial', 120, 'standard', '{}', 142, true, 1),
  ('Walk-In Freezer Repair', 'Commercial', 120, 'standard', '{}', 143, true, 1),

  -- Geothermal (4 services)
  ('Geothermal System Diagnostic', 'Geothermal', 60, 'standard', '{}', 144, true, 1),
  ('Geothermal Heat Pump Service', 'Geothermal', 120, 'scheduled', '{}', 145, true, 1),
  ('Geothermal Loop Inspection', 'Geothermal', 180, 'scheduled', '{}', 146, true, 1),
  ('Geothermal Installation', 'Geothermal', 480, 'scheduled', '{}', 147, true, 1),

  -- Hydronic (5 services)
  ('Hydronic Heating Diagnostic', 'Hydronic', 60, 'standard', '{}', 148, true, 1),
  ('Radiant Floor Heating Repair', 'Hydronic', 120, 'standard', '{}', 149, true, 1),
  ('Circulator Pump Replacement', 'Hydronic', 120, 'standard', '{}', 150, true, 1),
  ('Expansion Tank Replacement', 'Hydronic', 90, 'standard', '{}', 151, true, 1),
  ('Boiler Circulation Repair', 'Hydronic', 120, 'standard', '{}', 152, true, 1),

  -- Emergency (5 services)
  ('Emergency HVAC Repair', 'Emergency', 120, 'emergency', '{}', 153, true, 1),
  ('Emergency AC Repair', 'Emergency', 120, 'emergency', '{}', 154, true, 1),
  ('Emergency Heating Repair', 'Emergency', 120, 'emergency', '{}', 155, true, 1),
  ('No Heat Emergency Call', 'Emergency', 90, 'emergency', '{}', 156, true, 1),
  ('No Cooling Emergency Call', 'Emergency', 90, 'emergency', '{}', 157, true, 1);
